/**
 * @fileoverview gRPC-Web generated client stub for pubsub
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: pubsub.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.pubsub = require('./pubsub_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pubsub.PubSubServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pubsub.PubSubServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pubsub.PublishRequest,
 *   !proto.pubsub.PublishResponse>}
 */
const methodDescriptor_PubSubService_Publish = new grpc.web.MethodDescriptor(
  '/pubsub.PubSubService/Publish',
  grpc.web.MethodType.UNARY,
  proto.pubsub.PublishRequest,
  proto.pubsub.PublishResponse,
  /**
   * @param {!proto.pubsub.PublishRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pubsub.PublishResponse.deserializeBinary
);


/**
 * @param {!proto.pubsub.PublishRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pubsub.PublishResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pubsub.PublishResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pubsub.PubSubServiceClient.prototype.publish =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pubsub.PubSubService/Publish',
      request,
      metadata || {},
      methodDescriptor_PubSubService_Publish,
      callback);
};


/**
 * @param {!proto.pubsub.PublishRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pubsub.PublishResponse>}
 *     Promise that resolves to the response
 */
proto.pubsub.PubSubServicePromiseClient.prototype.publish =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pubsub.PubSubService/Publish',
      request,
      metadata || {},
      methodDescriptor_PubSubService_Publish);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pubsub.SubscribeRequest,
 *   !proto.pubsub.Message>}
 */
const methodDescriptor_PubSubService_Subscribe = new grpc.web.MethodDescriptor(
  '/pubsub.PubSubService/Subscribe',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.pubsub.SubscribeRequest,
  proto.pubsub.Message,
  /**
   * @param {!proto.pubsub.SubscribeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pubsub.Message.deserializeBinary
);


/**
 * @param {!proto.pubsub.SubscribeRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pubsub.Message>}
 *     The XHR Node Readable Stream
 */
proto.pubsub.PubSubServiceClient.prototype.subscribe =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pubsub.PubSubService/Subscribe',
      request,
      metadata || {},
      methodDescriptor_PubSubService_Subscribe);
};


/**
 * @param {!proto.pubsub.SubscribeRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pubsub.Message>}
 *     The XHR Node Readable Stream
 */
proto.pubsub.PubSubServicePromiseClient.prototype.subscribe =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pubsub.PubSubService/Subscribe',
      request,
      metadata || {},
      methodDescriptor_PubSubService_Subscribe);
};


module.exports = proto.pubsub;

